print("Bienvenido a tu simulador de aventuras.")
print()
print("¡Te haré un montón de preguntas y luego crearé una historia épica contigo como la estrella!")
print()

name = input("¿Cuál es su nombre? ")
enemy = input("¿Cuál es el nombre de tu peor enemigo? ")
superpower = input("¿Cuál es tu superpoder? ")
live_in = input("¿Donde vives? ")
favorite_food = input("¿Cuál es tu comida favorita? ")

print()
print("¡Hola\33[36m", name, "\33[0m! 🙂")
print("Tu capacidad de", superpower, "se asegurará de que nunca más tengas que mirar a\33[35m", enemy, "\33[0m.👿")
print("¡Ve a comer 🍽️", favorite_food, "mientras caminas 🚶🏽por las calles de", live_in, "y usa", superpower, "💪🏼 para el bien y no para el mal!")