user_name = input("¿Cuál es tu nombre? ")
live_in = input("¿De dónde eres? ")
favorite_food = input("¿Cuál es tu comida favorita? ")
favorite_music = input("¿Cuál es tu música favorita? ")
print()
print("¡Conociéndote!")
print("Te llamas")
print(user_name)
print("vives en ")
print(live_in)
print("Probablemente tengas ganas de comer ")
print(favorite_food)
print("mientras escuchas una canción de ")
print(favorite_music)