print("+--------------------------------------------------------------+")
print("|                                     📆 10 de octubre de 2022 | ")
print("|                                       Cañuelas, Buenos Aires |")
print("|  Querido yo:                                                 |")
print("|                                                              |")
print("|        Hoy me siento con muchas ganas de aprender Python.    |")
print("|        Espero poder aprovechar mucho es curso.               |")
print("|        Cuando veas esta carta recuerda todo lo que has       |")
print("|        avanzado desde que escribiste esto.                   |")
print("|                                                              |")
print("|        Sin otro particular, te saluda:                       |")
print("|                                            Agustín 😉        |")
print("|                                                              |")
print("+--------------------------------------------------------------+")
